### ISSUE TITLE
Proper website and Forum?

### ISSUE THREAD

**Issue by AHandheldFan** [salientos/salientos.github.io#7]
Hi. I think this distro is awesome. Any plans to make a better website and forum? and add somewhere where you can contact support?

**Comment by salientos** [comment]
> Hi. I think this distro is awesome. Any plans to make a better website and forum? and add somewhere where you can contact support?

There are plans for this in the future yes!

**Comment by AHandheldFan** [comment]
> > Hi. I think this distro is awesome. Any plans to make a better website and forum? and add somewhere where you can contact support?
> 
> There are plans for this in the future yes!

Glad to hear
